/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.NasabahController;

/**
 *
 * @author mzida
 */
public class ViewFormNasabah extends javax.swing.JFrame {

    /**
     * Creates new form ViewFormNasabahs
     */
    private NasabahController controller;
    private int selectedId = -1;
    Integer baris;
    
    
    public ViewFormNasabah() {
        initComponents();
        controller = new NasabahController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelForm = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jLabelAlamat = new javax.swing.JLabel();
        jTextFieldAlamat = new javax.swing.JTextField();
        jLabelNoHP = new javax.swing.JLabel();
        jTextFieldNoHP = new javax.swing.JTextField();
        jButtonTambah = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabelForm1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelForm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelForm.setText("Form Pendaftaran Nasabah");

        jLabelNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNama.setText("Nama      :");

        jTextFieldNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAlamat.setText("Alamat    :");

        jTextFieldAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelNoHP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNoHP.setText("No HP     :");

        jTextFieldNoHP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButtonTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahTambahNasabah(evt);
            }
        });

        jButtonHapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusHapusNasabah(evt);
            }
        });

        jButtonEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditEditNasabah(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearClearForm(evt);
            }
        });

        jLabelForm1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelForm1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelForm1.setText("Tabel Data Nasabah");

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelForm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonTambah)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNama)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAlamat)
                            .addComponent(jLabelNoHP))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAlamat)
                            .addComponent(jTextFieldNoHP))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelForm)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNama)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNoHP))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabelForm1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTambahTambahNasabah(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahTambahNasabah
        controller.insertNasabah();
    }//GEN-LAST:event_jButtonTambahTambahNasabah

    private void jButtonHapusHapusNasabah(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusHapusNasabah
        controller.hapusNasabah(baris);
        jTextFieldNama.setText("");
        jTextFieldAlamat.setText("");
        jTextFieldNoHP.setText("");
        selectedId = -1; 
        baris = null;    
    }//GEN-LAST:event_jButtonHapusHapusNasabah

    private void jButtonEditEditNasabah(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditEditNasabah
        controller.editNasabah();
    }//GEN-LAST:event_jButtonEditEditNasabah

    private void jButtonClearClearForm(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearClearForm
        jTextFieldNama.setText("");
        jTextFieldAlamat.setText("");
        jTextFieldNoHP.setText("");
        selectedId = -1; 
        baris = null;    
    }//GEN-LAST:event_jButtonClearClearForm

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        baris = jTable1.getSelectedRow();

        selectedId = Integer.parseInt(
            jTable1.getValueAt(baris, 0).toString()
        );

        jTextFieldNama.setText(
            jTable1.getValueAt(baris, 1).toString()
        );

        jTextFieldAlamat.setText(
            jTable1.getValueAt(baris, 2).toString()
        );
        
        jTextFieldNoHP.setText(
            jTable1.getValueAt(baris, 3).toString()
        );
    }//GEN-LAST:event_jTable1MouseClicked

    // Ambil Input dari View
    
    public int getSelectedId(){
        return selectedId;
    }
    
    public String getInputNama(){
        return jTextFieldNama.getText();
    }
    
    public String getInputAlamat(){
        return jTextFieldAlamat.getText();
    }
    
    public String getInputNoHP(){
        return jTextFieldNoHP.getText();
    }
    
    public javax.swing.JTable getTableNasabah(){
        return jTable1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabelAlamat;
    private javax.swing.JLabel jLabelForm;
    private javax.swing.JLabel jLabelForm1;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNoHP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNoHP;
    // End of variables declaration//GEN-END:variables
}
